channels:
    - conda-forge
    - ucb-bar
    - nodefaults

platforms:
    - linux-64

dependencies:
    # required for lockfile generation
    - conda-lock=2.5.7
    - qemu # from ucb-bar channel - https://github.com/ucb-bar/qemu-feedstock
    - python>=3.9,<3.11
    - rsync
    - psutil
    - doit>=0.34.0
    - git
    - gitpython
    - humanfriendly
    - ctags
    - bison
    - flex
    - expat
    - make
    - pyyaml
    - pip
    - bc
    - sphinx
    - sphinx_rtd_theme
    - unzip
    - gcc=13.2
    - gxx=13.2
    - conda-gcc-specs
    - binutils
    - sysroot_linux-64=2.17
    - patch
    - which
    - sed
    - make
    - diffutils
    - bash
    - gzip
    - bzip2
    - perl
    - tar
    - file
    - wget
    - findutils
    - lzop
    - pygithub
    - autoconf
