channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _anaconda_depends
  - python=3.12
  - decorator
  - pandas
  - setuptools
  - pip
  - wheel
  - anaconda-anon-usage
  - anaconda-catalogs
  - anaconda-client
  - anaconda-project
  - anaconda-navigator
  - conda[version='>=23.7']
  - conda-build
  - conda-content-trust
  - conda-libmamba-solver
  - conda-pack
  - conda-package-handling
  - conda-package-streaming
  - conda-token
  - mesa
  - qt
  - libopengl
  - mesalib
  - pre-commit
  - scons
  - apptainer
  - git-filter-repo

