// Generated by CIRCT firtool-1.75.0
module Core(	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:23:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:23:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:23:7]
  output        io_imem_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  output [31:0] io_imem_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input         io_imem_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input  [31:0] io_imem_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  output        io_dmem_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  output [31:0] io_dmem_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  output [31:0] io_dmem_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  output        io_dmem_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  output [2:0]  io_dmem_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input         io_dmem_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input  [31:0] io_dmem_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input         io_interrupt_debug,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input         io_interrupt_mtip,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input         io_interrupt_msip,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input         io_interrupt_meip,	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
  input         io_hartid	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:25:15]
);

  wire [31:0] _d_io_dat_dec_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_dec_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_exe_br_eq;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_exe_br_lt;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_exe_br_ltu;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire [3:0]  _d_io_dat_exe_br_type;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_exe_inst_misaligned;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_mem_ctrl_dmem_val;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_mem_data_misaligned;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_mem_store;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_csr_eret;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _d_io_dat_csr_interrupt;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
  wire        _c_io_ctl_dec_stall;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_full_stall;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [1:0]  _c_io_ctl_exe_pc_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [3:0]  _c_io_ctl_br_type;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_if_kill;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_dec_kill;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [1:0]  _c_io_ctl_op1_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [2:0]  _c_io_ctl_op2_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [3:0]  _c_io_ctl_alu_fun;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [1:0]  _c_io_ctl_wb_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_rf_wen;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_mem_val;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [1:0]  _c_io_ctl_mem_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [2:0]  _c_io_ctl_mem_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [2:0]  _c_io_ctl_csr_cmd;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_fencei;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_pipeline_kill;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire        _c_io_ctl_mem_exception;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  wire [31:0] _c_io_ctl_mem_exception_cause;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  CtlPath c (	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .clock                      (clock),
    .reset                      (reset),
    .io_dmem_resp_valid         (io_dmem_resp_valid),
    .io_dat_dec_inst            (_d_io_dat_dec_inst),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_dec_valid           (_d_io_dat_dec_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_exe_br_eq           (_d_io_dat_exe_br_eq),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_exe_br_lt           (_d_io_dat_exe_br_lt),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_exe_br_ltu          (_d_io_dat_exe_br_ltu),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_exe_br_type         (_d_io_dat_exe_br_type),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_exe_inst_misaligned (_d_io_dat_exe_inst_misaligned),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_mem_ctrl_dmem_val   (_d_io_dat_mem_ctrl_dmem_val),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_mem_data_misaligned (_d_io_dat_mem_data_misaligned),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_mem_store           (_d_io_dat_mem_store),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_csr_eret            (_d_io_dat_csr_eret),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_dat_csr_interrupt       (_d_io_dat_csr_interrupt),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .io_ctl_dec_stall           (_c_io_ctl_dec_stall),
    .io_ctl_full_stall          (_c_io_ctl_full_stall),
    .io_ctl_exe_pc_sel          (_c_io_ctl_exe_pc_sel),
    .io_ctl_br_type             (_c_io_ctl_br_type),
    .io_ctl_if_kill             (_c_io_ctl_if_kill),
    .io_ctl_dec_kill            (_c_io_ctl_dec_kill),
    .io_ctl_op1_sel             (_c_io_ctl_op1_sel),
    .io_ctl_op2_sel             (_c_io_ctl_op2_sel),
    .io_ctl_alu_fun             (_c_io_ctl_alu_fun),
    .io_ctl_wb_sel              (_c_io_ctl_wb_sel),
    .io_ctl_rf_wen              (_c_io_ctl_rf_wen),
    .io_ctl_mem_val             (_c_io_ctl_mem_val),
    .io_ctl_mem_fcn             (_c_io_ctl_mem_fcn),
    .io_ctl_mem_typ             (_c_io_ctl_mem_typ),
    .io_ctl_csr_cmd             (_c_io_ctl_csr_cmd),
    .io_ctl_fencei              (_c_io_ctl_fencei),
    .io_ctl_pipeline_kill       (_c_io_ctl_pipeline_kill),
    .io_ctl_mem_exception       (_c_io_ctl_mem_exception),
    .io_ctl_mem_exception_cause (_c_io_ctl_mem_exception_cause)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
  DatPath d (	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
    .clock                      (clock),
    .reset                      (reset),
    .io_imem_req_valid          (io_imem_req_valid),
    .io_imem_req_bits_addr      (io_imem_req_bits_addr),
    .io_imem_resp_valid         (io_imem_resp_valid),
    .io_imem_resp_bits_data     (io_imem_resp_bits_data),
    .io_dmem_req_valid          (io_dmem_req_valid),
    .io_dmem_req_bits_addr      (io_dmem_req_bits_addr),
    .io_dmem_req_bits_data      (io_dmem_req_bits_data),
    .io_dmem_req_bits_fcn       (io_dmem_req_bits_fcn),
    .io_dmem_req_bits_typ       (io_dmem_req_bits_typ),
    .io_dmem_resp_bits_data     (io_dmem_resp_bits_data),
    .io_ctl_dec_stall           (_c_io_ctl_dec_stall),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_full_stall          (_c_io_ctl_full_stall),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_exe_pc_sel          (_c_io_ctl_exe_pc_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_br_type             (_c_io_ctl_br_type),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_if_kill             (_c_io_ctl_if_kill),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_dec_kill            (_c_io_ctl_dec_kill),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_op1_sel             (_c_io_ctl_op1_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_op2_sel             (_c_io_ctl_op2_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_alu_fun             (_c_io_ctl_alu_fun),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_wb_sel              (_c_io_ctl_wb_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_rf_wen              (_c_io_ctl_rf_wen),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_mem_val             (_c_io_ctl_mem_val),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_mem_fcn             (_c_io_ctl_mem_fcn),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_mem_typ             (_c_io_ctl_mem_typ),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_csr_cmd             (_c_io_ctl_csr_cmd),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_fencei              (_c_io_ctl_fencei),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_pipeline_kill       (_c_io_ctl_pipeline_kill),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_mem_exception       (_c_io_ctl_mem_exception),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_ctl_mem_exception_cause (_c_io_ctl_mem_exception_cause),	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:26:19]
    .io_dat_dec_inst            (_d_io_dat_dec_inst),
    .io_dat_dec_valid           (_d_io_dat_dec_valid),
    .io_dat_exe_br_eq           (_d_io_dat_exe_br_eq),
    .io_dat_exe_br_lt           (_d_io_dat_exe_br_lt),
    .io_dat_exe_br_ltu          (_d_io_dat_exe_br_ltu),
    .io_dat_exe_br_type         (_d_io_dat_exe_br_type),
    .io_dat_exe_inst_misaligned (_d_io_dat_exe_inst_misaligned),
    .io_dat_mem_ctrl_dmem_val   (_d_io_dat_mem_ctrl_dmem_val),
    .io_dat_mem_data_misaligned (_d_io_dat_mem_data_misaligned),
    .io_dat_mem_store           (_d_io_dat_mem_store),
    .io_dat_csr_eret            (_d_io_dat_csr_eret),
    .io_dat_csr_interrupt       (_d_io_dat_csr_interrupt),
    .io_interrupt_debug         (io_interrupt_debug),
    .io_interrupt_mtip          (io_interrupt_mtip),
    .io_interrupt_msip          (io_interrupt_msip),
    .io_interrupt_meip          (io_interrupt_meip),
    .io_hartid                  (io_hartid)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/core.scala:27:19]
endmodule

