// Generated by CIRCT firtool-1.75.0
// VCS coverage exclude_file
module regfile_32x32(	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
  input  [4:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [31:0] R0_data,
  input  [4:0]  R1_addr,
  input         R1_en,
  input         R1_clk,
  output [31:0] R1_data,
  input  [4:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:31];	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
  always @(posedge W0_clk) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
    if (W0_en & 1'h1)	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
      Memory[W0_addr] <= W0_data;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
    reg [31:0] _RANDOM_MEM;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
    initial begin	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
      `INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
      `ifdef RANDOMIZE_MEM_INIT	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM_MEM = `RANDOM;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
          Memory[i[4:0]] = _RANDOM_MEM;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/rv32_5stage/regfile.scala:35:21]
endmodule

