name: Gemmini CI

on: [push]

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  REMOTE_WORK_DIR: /scratch/buildbot/gemmini-ci-shared/gemmini-${{ github.sha }}
  JAVA_TMP_DIR: /tmp/gemmini-${{ github.sha }}-full

jobs:
  install-gemmini:
    runs-on: jktqos
    steps:
      - name: Delete old checkout
        run: |
            rm -rf ${{ github.workspace }}/* || true
            rm -rf ${{ github.workspace }}/.* || true
      - uses: actions/checkout@v3
      - name: Setup repository
        run: |
          .github/scripts/install-gemmini.sh

  spike-run-tests:
    runs-on: jktqos
    needs: install-gemmini
    steps:
      - name: Delete old checkout
        run: |
            rm -rf ${{ github.workspace }}/* || true
            rm -rf ${{ github.workspace }}/.* || true
      - uses: actions/checkout@v3
      - name: Run Gemmini Spike tests
        run: |
          .github/scripts/run-tests-spike.sh

  build-gemmini-config:
    runs-on: jktqos
    needs: install-gemmini
    steps:
      - name: Delete old checkout
        run: |
            rm -rf ${{ github.workspace }}/* || true
            rm -rf ${{ github.workspace }}/.* || true
      - uses: actions/checkout@v3
      - name: Building Gemmini Config using Verilator
        run: |
          .github/scripts/do-rtl-build.sh

  rtl-run-tests:
    runs-on: jktqos
    needs: build-gemmini-config
    steps:
      - name: Delete old checkout
        run: |
            rm -rf ${{ github.workspace }}/* || true
            rm -rf ${{ github.workspace }}/.* || true
      - uses: actions/checkout@v3
      - name: Run Gemmini Config tests using Verilator
        run: |
          .github/scripts/run-tests-rtl.sh

  cleanup:
    name: cleanup
    needs: [spike-run-tests, rtl-run-tests]
    runs-on: jktqos
    if: ${{ always() }}
    steps:
      - name: Delete repo copy
        run: |
           rm -rf ${{ env.REMOTE_WORK_DIR }}
           rm -rf ${{ env.JAVA_TMP_DIR }}
