on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

env:
  VERILATOR_VERSION: v5.026

jobs:
  test:
    name: Test
    runs-on: self-hosted
    container:
      image: jwere/assassyn-dev:v0.0.1
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Python Frontend Unit Tests
        env:
          PYTHONPATH: ${{ github.workspace }}/python
          ASSASSYN_HOME: ${{ github.workspace }}
        run: |
          pytest -n 8 python/unit-tests;
          python3 examples/systolic-array/systolic_array.py;
          python3 examples/systolic-array/memory_systolic_array.py;
          python3 examples/minor-cpu/src/main.py;
          python3 examples/minor-cpu/src/br_pre_main.py;
          python3 examples/priority-queue/main.py;
