[package]
name = "assassyn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab = "0.4.8"
paste = "1.0"
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
regex = "1.5"
