name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - 1.6.x
      - 1.5.x
      - 1.4.x
      - 1.3.x

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install Verilator
        run: sudo apt-get update -y && sudo apt-get install -y verilator
      - name: Setup Scala
        uses: coursier/setup-action@v1
      - name: Cache
        uses: coursier/cache-action@v6
      - name: Formatting check
        id: scalafmt
        run: sbt scalafmtCheckAll
      - name: Documentation
        id: doc
        run: sbt doc
      - name: Test
        id: test
        run: sbt +test
      # Publishing steps
      # These steps are here to avoid duplicated work and logic
      - name: Setup GPG (for Publish)
        id: publish_start
        # on.push.branches above enforces we only publish from correct branches
        if: github.event_name == 'push'
        uses: olafurpg/setup-gpg@v3
      - name: Publish
        # publish_start if guards this step
        if: steps.publish_start.outcome != 'skipped'
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  # Sentinel job to simplify how we specify which checks need to pass in branch
  # protection and in Mergify
  #
  # When adding new jobs, please add them to `needs` below
  all_tests_passed:
    name: "all tests passed"
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success!

