#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: main

# STEP: vivado_flow
cd /home/gaod/isca25_ae/assassyn-workloads/MachSuite
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /home/gaod/isca25_ae/assassyn-workloads/MachSuite/HLS_output//Synthesis/vivado_flow/vivado.tcl


